FROM public.ecr.aws/lambda/python:3.13

RUN dnf install -y gcc

COPY ./src/python/api/requirements.txt .
COPY ./src/python/api ./
COPY ./src/python/lambda_utils ./lambda_utils

RUN pip install -r requirements.txt

CMD ["main.handler"]