FROM python:3.13

# Set the working directory to /app/api
WORKDIR /app

# Copy the Python source code
COPY ./src/python/api /app/
COPY ./src/python/lambda_utils /app/lambda_utils

# Install dependencies from requirements.txt 
RUN pip install --no-cache-dir -r /app/requirements.txt

# Start uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]