FROM python:3.12

COPY ./src/python/api /app
COPY ./src/python/lambda_utils /app/lambda_utils

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]