[tool.poetry]
name = "cue-backend"
version = "0.1.0"
description = "AWS code and infrastucture for the CUE enterprise product"
authors = ["Navaneeth Selvaraj <ns0066@uah.edu>", "Davis Gaunt <bdg0015@uah.edu>"]
license = "Apache-2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "~0.112.2"
pydantic = {extras = ["email"], version = "~2.8.2"}  
uvicorn = "~0.30.6"
python-dotenv = "~1.0.1"
mangum = "~0.17.0"
boto3 = "~1.35.7"
asyncpg = "^0.30.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"} # Added: For JWT
warrant = "^0.6.1"  # Added: For Cognito SRP
requests = "^2.32.3" # Added for jwks fetch
structlog~=25.4.0
httpx~=0.28.1
aws-xray-sdk~=2.14.0

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
pytest-asyncio = "^0.23.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]  # Add this section for pytest configuration
asyncio_mode = "auto"
pythonpath = [
  ".", "src/python"
]
testpaths = ["tests", "src/python/api/tests"]
addopts = "-v -s --tb=short --cov=src/python --cov-report term-missing --cov-fail-under=80"